### ISSUE TITLE
Status page fails when image transformation cache path is not writable

### ISSUE THREAD

**Issue by christeredvartsen** [imbo/imbo#316]
When someone has enabled the `ImageTransformationCache` event listener, and the specified path is not writable by the webserver, the `/status` endpoint fails in telling the user agent that something is wrong with the storage. Instead it fails with a Fatal error since it's an uncaught exception.

Perhaps the writable checks should be moved from the `__construct` method of the event listener to some other method, so that at least the `/status` endpoint ends up giving a valid response to the user agent?

**Comment by fangel** [comment]
I'd 👍 the request for some sort of pluggable status-page, so that extensions for Imbo can also be monitored using the `/status`-page.
One obvious extension is whether or not the metadata-search plugin can reach it's backend.

If something like the federated storage adapter makes it in as well, it would be quite useful to have detailed status about the different storage-engines, and not just a overall yes/no on the storage.
