### ISSUE TITLE
New access control implementation

### ISSUE THREAD

**Issue by rexxars** [imbo/imbo#319]
We recently introduced RW/RW private keys, which took us a step further.

Going forward, we're encountering new resources and use cases which will need more fine-grained access control. Examples of this:

- `/status` could possibly need some access control, if we add more status reporting from various event listeners
- `/stats` provides statistics for many different public keys and is currently behind an IP-whitelist, but being able to access this from any IP with the right credentials seems like a good idea
- `/images` will fetch/search for images within all public keys (or the ones specified)
- `/users/<user>/images/<imageId>/metadata` should possibly be writable by a user which cannot write to the `/images`-endpoint of the same user

@matslindh has some thoughts on this, and I'd like to start discussing how we can implement this ASAP, as I'm about to start work on the global `/images` endpoint now.

**Comment by rexxars** [comment]
I'm not in love with the "master key" key approach. I've discussed this briefly with @kbrabrand and we're thinking perhaps the best approach is to let the CLI tool be able to create new public and private keys, regardless of backend.

Basically, it would check if the access control adapter configured is mutable (database or similar). If mutable, prompt for public and private key (alternatively letting Imbo generate a private key), then a list of resources to grant access to.

Thoughts? @matslindh ?

**Comment by matslindh** [comment]
I'm not fond of the CLI tool being the only way of users, although I'm sure we could move the REST API part of it to a plugin instead of having it in core.

I see the possibility of having a separate web interface to manage your Imbo server as a long-term goal for the server, and being unable to CRUD-ing users through the API will make that hard (except for a custom plugin, which might be the next best way of implementing this anyway).

Another option is to extend the existing configuration with an 'admin' ('ro', 'rw', 'admin') to allow a public/private key to manipulate common server data.

**Comment by rexxars** [comment]
The rest API already supports adding keys - the only thing I'm not fond of here is the initial creation of an admin user. I just don't like having a public and private key for a "master user" in the configuration, is all.

**Comment by matslindh** [comment]
Ah. Agreed. Remove it from the configuration and use the CLI tool when setting it up for the first time.

**Comment by rexxars** [comment]
The beta2.0 branch is now based on the access control implementation that was worked on in #328. I'm closing this and will create separate issues for the remaining work related to it.
