### ISSUE TITLE
Catching Errors

### ISSUE THREAD

**Issue by daveyand** [imbo/imbo#322]
Hi there

I'm using Imbo with nginx and i'm trying to catch the 40x and 50x errors that Imbo fires out. I do not like the default error view as i feel it exposes too much and i'd like to just replace it with a standard error document. 

So far i have: 
error_page 403 /errors/403.html;
error_page 404 /errors/404.html;
error_page 405 /errors/405.html;
error_page 400 /errors/error.html;
error_page 500 501 502 503 504 /error/5xx.html;

location ^~ /errors/ {
    internal;
    root /var/www/;
}

within nginx and i'm firing a 400 error, but nothing is being triggered and i still get the standard imbo page. 

Is there an easier way to handle imbo errors?

**Comment by matslindh** [comment]
If I remember correctly you'll have to specify [`fastcgi_intercept_errors`](http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_intercept_errors) for the backend if you want to replace the error page with your own, otherwise nginx will forward the generated content to the client.

We might want to consider a configurable "not any more information than the HTTP status"-error page, though.

**Comment by christeredvartsen** [comment]
Configuring the amount of data on error pages seems like a nice addition to me.

**Comment by daveyand** [comment]
@matslindh that worked, thanks
