### ISSUE TITLE
SmartSize: Transparently degrade to "dumb" resize if no POI

### ISSUE THREAD

**Issue by rexxars** [imbo/imbo#372]
I think one of the coolest features of the SmartSize transformation is that it can read the POI-data from metadata. This allows tasks such as feature detection (faces etc) to work in the background and simply update the metadata for the image when its computations are complete.

What this allows is for the user to basically just say: I want the best version Imbo can give me of this image, with these dimensions.

Currently, the transformation fails when no POI is defined in the URL or in metadata. Personally, I would rather it gracefully degraded to a "dumb" resize - using either `maxSize` + `canvas` or `maxSize` + `crop`.

**Comment by matslindh** [comment]
We should append a response header in that case, so that the client still can detect the failed POI resize. Something like X-Imbo-POI-Resize: fallback or similar.

**Comment by rexxars** [comment]
Good point. Or perhaps always append an `X-Imbo-POI-Count: <number-of-pois>`. If 0, that would explain the fallback.

**Comment by kbrabrand** [comment]
I've implemented this in the PR. The response now includes an `X-Imbo-POIs-Used` header. The value is either 0 or 1, because the smart size transformation algorithm currently supports only one POI.

We discussed whether to include the total number of POIs on the picture, but since it would us to query for metadata on each resize (even if specified as a transformation param) I went with the inexpensice and simple approach of returning how many was used in the transformation.
