### ISSUE TITLE
Investigate indexed array query params + access tokens

### ISSUE THREAD

**Issue by rexxars** [imbo/imbo#428]
Currently, an accesstoken generated with `t[]=foo&t[]=bar` will not be valid for `t[0]=foo&t[1]=bar`. This seems to cause some issues in some cases - one of them being reconstructed URLs where libraries don't maintain the original "indexless" query style.

We should investigate and see if there is a simple workaround we could do that makes both valid.

**Comment by christeredvartsen** [comment]
Btw, do the official clients generate the same query string with regards to indexes? If not, they should.

**Comment by sgulseth** [comment]
The Javascript client generates t[] while php generates t[0]

**Comment by christeredvartsen** [comment]
Since the Imbo-server has no way of knowing of the URL has been changed with regards to these indexes after some client generated it the only way to make sure the hash is correct is to have Imbo regenerate the access token for the URL with and without the indexes and see if one of the two matches. This feels somewhat dirty, but I can't see any other possibilities.

**Comment by matslindh** [comment]
We'll need to verify both for a while, but we should really try to make all the official clients use the `t[]` syntax, and then add a deprecation error for any indexed array using explicit indices.

**Comment by sgulseth** [comment]
@matslindh Facebook parses t[] and converts them to t[INDEX], so if we remove the verification of both syntaxes sharing of Imbo images on Facebook would fail.

**Comment by christeredvartsen** [comment]
Fixed in imbo-2.2.0 (#475).
