### ISSUE TITLE
dbal dependence

### ISSUE THREAD

**Issue by serieznyi** [imbo/imbo#472]
Why `docktrine/dbal` package not in imbo composer dependencies, but he used in [code](https://github.com/imbo/imbo/blob/develop/library/Imbo/Database/Doctrine.php#L19)?

**Comment by kbrabrand** [comment]
It's there as a suggested/optional dependency. When installing it suggests different packages that you might want to install. 

But since mongo/doctrine/s3 and so on is dependent on the configuration, it makes a lot more sense making it optional since very few people will be using them all. 

Also, the install size would be a lot bigger than necessary if all suggested deps were installed.

**Comment by serieznyi** [comment]
@kbrabrand Maybe be good idea move "suggested/optional" classes in external libraries? 
And in project use only one default db driver (e.x MongoDb).

**Comment by christeredvartsen** [comment]
@serieznyi We discussed this a while back, but it will somewhat make all of these libraries harder to maintain and test with regards to Imbo-integration. We also talked about moving "suggested/optional" stuff that rely on PHP-extensions out to external libs (for instance the caching stuff that requires the memcached extension), which we most likely will do from Imbo-3.0.

The suggested way of installing Imbo will easily let you include these optional packages anyways, if you plan on using the dbal stuff for instance.
