### ISSUE TITLE
Last modified timestamp not updated when updating metadata using the Doctrine adapter

### ISSUE THREAD

**Issue by fangel** [imbo/imbo#530]
I stumbled upon a discrepancy in the Doctrine database-adapter, namely that it the `updateMetadata` and `deleteMetadata` methods doesn't update the `modified`-timestamp of the image.

This is, however, the case for the Mongo and MongoDB adapters.

As an example, look at the`updateMetadata`-methods for the Mongo and MongoDB adapters: https://github.com/imbo/imbo/blob/develop/src/Database/Mongo.php#L201 + https://github.com/imbo/imbo/blob/develop/src/Database/MongoDB.php#L185 where the `updated`-property gets updated to `time()`

If we compare this to the `updateMetadata`-method of the Doctrine adapter, we can see that such an update does not occur: https://github.com/imbo/imbo/blob/develop/src/Database/Doctrine.php#L158-L184

---

In the IRC-channel, it was discussed changing the interface for the database-class to include a method to explicitly update the last-modified timestamp, and then have it be the responsibility of the resource-handlers to update the timestamp when necessary.

My proposal would be to bug-fix the Doctrine adapter for Imbo 2.x, and then modify the `Imbo\Database\DatabaseInterface`-interface and the adapters for Imbo 3.x (since I would classify modifying that interface as breaking BC, as someone could have made their own database-adapter based on the interface.

If you agree, I'll create two PRs with the bug-fix + update.

-Morten.

**Comment by christeredvartsen** [comment]
Sorry for not replying to this sooner.

I think this sounds like a nice addition. Do you have anything to add @matslindh?

**Comment by matslindh** [comment]
👍  - I want the logic of "updating metadata updates the timestamp of the image" to part of the general flow instead of up to the adapter, so the different strategies for Imbo2 and Imbo3 seems sane.

**Comment by matslindh** [comment]
I'd prefer if we kept the notion of time in the method name, so that it's clear that we're updating the timestamp of when the image was updated - and not just saying that it has been updated. How about something like `setUpdatedTimeNow($user, $imageIdentifier)` - this will allow us to introduce a `setUpdatedTime` later if necessary.

**Comment by matslindh** [comment]
PHP doesn't allow function calls as default parameters - so we'd have to do `$time = null` and make all the adapters assume that this means the current time. In that case I'd prefer if we implemented two methods, one for `setUpdatedTime` and one for `setUpdatedTimeNow` (or `setUpdatedNow` which I might prefer) - since we don't have an abstract class here (but this could be a case for introducing one), we can't automagically provide an implementation for `setUpdatedTimeNow()` as `setUpdateTime(..., $timestring)`.

**Comment by fangel** [comment]
I'll introduce `setUpdatedTime` and `setUpdatedNow` in the interface - but I might skip adding in an abstract class if that's okay for now.

**Comment by fangel** [comment]
I've created a PR (#598) now - I changed the method names to `setLastModifiedNow` and `setLastModifiedTime` because there was a already existing method called `getLastModified` so I figured I'd stick to that naming.
