### ISSUE TITLE
Video handling and transformation

### ISSUE THREAD

**Issue by Remo** [imbo/imbo#563]
Added imbo as a backend for a project I'm working on. An hour after I told my customer about my test they wanted to upload a video. Have to admit that I didn't think that far right away, but I can understand that he did it. I'm aware that this currently doesn't work, but I wonder whether it's a good idea to keep going that way:

* Are you interested in supporting video files? Creating thumbnails is a pretty common task and maybe converting between various formats would be interesting for others too.
* Are files processed in a memory efficient way? Does PHP need memory to keep the whole file in a single variable? I wouldn't want to give my PHP process 4GB of memory just to display a 1GB video.

Should I try to add this or is this a bad idea?

**Comment by matslindh** [comment]
It'll need a whole lot of changes, that's for sure - everything so far as been assumed to be handling of single framed files, but we have experimented with supporting operations on animated gifs. Since we use ImageMagick as the current backend, we'll have to add a separate backend that supports the same operations with video files instead. I'll at least add my thoughts...

That being said, generating thumbnails could currently be implemented in the same way as my experimental PDF / vector support, by uploading the file and extracting one or more rasterized images. My guess would be that we could have the video file as the backend, then implement a custom loader that reads a timestamp as well, and then applies the transformation chain based on that single image. That way we can keep the change localized to loader code, instead of having to support videos all the way through the processing chain. 

Another option is to introduce a /videos/ endpoint as well, but that would be quite a large task (it's completely solvable, but we'll have to decide a few larger issues, such as which library to use for processing and transformations).

Most video processing libraries only need to load the metadata and find the closest keyframe, then interpolate from that. But we might have to have the whole file locally, i.e. not allow searching directly from the S3 or B2 backend.

A different issue is also that we currently rely heavily on Varnish or other caches to avoid performing a lot of repeat work in Imbo, but we'd probably want to stash the cache to a publicly available location (and in a CDN) for video support (so we can 302/301 to the location and serve the file, or use X-Sendfile - but we probably want to have some way to serve these files without specific httpd feature support).

**Comment by Remo** [comment]
Thanks for your detailed answer!

Is your experimental PDF / vector support in a public git repo? Would be interesting to see the changes you've had to make to add another backend.

The more I play with imbo and the longer I talk about the project I'm working on, the more I feel like I need something slightly different. It looks like I need a generic file backend. Our application is using VueJS a lot and the REST API you guys built felt like the perfect choice. It's not clear to us yet, but we probably need a rather generic REST based file storage. Something where we can upload a PDF document and maybe just get an icon resembling a PDF document back and an option to download the original file. Basically no transformation for a number of file types and a few transformations for pictures and possibly videos.

I don't feel like building my own REST API file storage, but I'm also a bit hesitant to really start with imbo as my requirements seems to be slightly different. Maybe I could spend the time I'd need to build our own REST API storage to add some features to imbo. If there's a way to build a package to add a generic file handling I would certainly consider it!

**Comment by matslindh** [comment]
I think you might be looking for something like [Ceph](http://ceph.com/) which is compatible with S3 clients - allowing you to have your own object / file storage with a well defined S3 API. There's a lot of other services that provide the same. We only do images, but we do a lot more with the images than just storage. Imbo is perfectly suited to situations where you need to use the images in a multitude of different sizes, crops and similar, where there is no well-defined (and even then) set of sizes you'll need from the start.

I don't have the PDF branch available at the moment, but in general it needs a small fix in the Images handler to allow for the new mime type, and a delegated loader (.. which at the moment has to be hacked into the sequence of plugins, iirc) that returns raster data for further processing. Since the branch had been idle for a very long time and I have a better idea of how to implement this now (.. we'll need pluggable loaders and custom parameters for extracting a particular page/region, and we'll have to decide how to handle physical sizes vs rasterized sizes), the work will have be to redone anyways.

For your use case I'd stash everything in Ceph (locally) or S3/B2 (remote), and then stash my images in Imbo as well, so that I could retrieve custom sized and cropped version on demand. You can also use the S3 backend to store Imbo's data in Ceph.

**Comment by Remo** [comment]
Yes, maybe something like ceph would suit me better, but I do require some more advanced image functions.

I'll see, maybe I'll do some imbo hacking, maybe I'll go with something like ceph or come up with something completely custom, but thanks for your detailed answer!

**Comment by christeredvartsen** [comment]
@Remo You could just have Imbo write images to the same ceph storage cluster, and let Imbo deal with storing/delivering images, and have some other service deal with storing/delivering other files.

**Comment by christeredvartsen** [comment]
Closing this issue for now.
