### ISSUE TITLE
https issues.  Need help

### ISSUE THREAD

**Issue by DifsonApps** [imbo/imbo#599]
Hello,

I would like to use Imbo in https.

Here is my configuration of origin

$ client = ImboClient \ ImboClient :: factory (array (
        'serverUrls' => ['http: // mydomain: 86'],
        'publicKey' => 'mypublickey',
        'privateKey' => 'myprivatekey',
        'user' => 'myImboUser'
    ));

My Imbo server is on port 86. so to access it, I have to do http: // mydomain: 86 and it works fine.

I set up this proxy on my VirtualHost https

 ProxyPass "/imbo_secur" "http://mydomain:86"
 ProxyPassReverse "/imbo_secur" "http://mydomain:86"
 
and when I do https://mydomain/imbo_secur, and it works

 when i call this url
 
 http://mydomain:86/users/myImboUser/images/<ImageID>/publicKey=<mypublickey>&accessToken=<userTocken>
 
 I get the picture
 
 When I replace with https with the same tocken, I always have the image

 https://mydomain/imbo_secur/users/myImboUser/images/<ImageID>/publicKey=<mypublickey>&accessToken=<userTocken>

 But when I change my configuration to put the https
 'serverUrls' => ['https://mydomain/imbo_secur']
and I call this url

https://mydomain/imbo_secur/users/myImboUser/images/<ImageID>/publicKey=<mypublickey>&accessToken=<httpsuserTocken>

I have an error 400 "Incorrect access token"
 

 
 I added trustedProxies as shown in this link https://github.com/imbo/imbo/issues/337
 but no change.
 
 'trustedProxies' => ['mydomain_Ip']
 
 What did I miss?

**Comment by matslindh** [comment]
If you generated the URL in your client with the protocol being set to `http` (as you did), the `http` part will by default be used in the signing token as well - which is why it fails.

With the default settings for how the protocol is handled when generating tokens, just setting `trustedProxies` is not enough - the proxy will also have to include the `X-Forwarded-Proto` header with its value being set to `https`. 

You can change this on the server side by making imbo try with both `http` and `https` [when verifying the accessToken](https://imbo.readthedocs.io/en/latest/installation/configuration.html#authentication-protocol-authentication).

You can also configure the endpoint in Apache to set the protocol if the endpoint is only available over `https`:

```
<VirtualHost ...>
    RequestHeader set X-Forwarded-Proto "https"

    ...
</VirtualHost>
```

**Comment by christeredvartsen** [comment]
@DifsonApps Did the suggestion above fix your issue?

**Comment by matslindh** [comment]
@DifsonApps I'll close this issue for now, please re-open if you're still having issues.
